export const workspaceGuide = [
  'In Documents, create HaruCourse with Practice, Projects and Evidence folders. Keep one folder per lesson inside Practice; keep each project inside Projects.',
  'Open a local text editor such as Notepad. Save notebook.md in HaruCourse. Plain text is sufficient: record the lesson, file location, decision, evidence limits and next action.',
  'Save evidence-log.md in Evidence. Use columns: ID | source and date | observation | interpretation | artifact location | permission and limits. Keep participant identities and consent records separately and privately.',
  'For a lesson, open its Bring artifact, create the named work folder, then copy its starter into work.md. Brackets are placeholders for your own work, not supplied findings.',
  'For paper work, label each sheet and keep originals. If a camera is available, capture readable images with even light. Save original and revised versions separately; a photo is documentation, not a working interface.',
  'Use My work for the artifact reference, reflection and next action. A file path does not upload anything or synchronize external files. Keep a backup of your work folder using your existing storage.',
  'For review from another device, use an existing free sharing method and check the reviewer can open only the intended anonymized files. Never make participant data public to obtain feedback.',
];

export const figmaGuide = [
  'Optional route: open figma.com and sign in to a free Starter account. Decline upgrades and trials. If an assigned control is unavailable, use the paper route; no paid feature is required.',
  'Create a Design file in Drafts and rename it with the lesson ID. Use the Frame tool (F) to draw a screen boundary; set its width and height in the right panel. A frame groups one screen’s content.',
  'Use Text (T) for actual labels and Rectangle (R) for control boundaries. Select a layer to edit text size, fill and dimensions in the right panel. Start with these tools, not plugins or generated UI.',
  'Duplicate the frame before revising. Name the frames Before and After, or use the state IDs from your flow. For layout comparisons, duplicate again and change width; reposition content deliberately. A static frame does not prove browser reflow.',
  'To export, select the frame, find Export in the right panel, add an export setting, choose PNG and export. Open the downloaded image to check readable labels and uncropped content; keep it beside work.md.',
  'This route is documented but has not been tested in a signed-in Starter account for this release. Paper is the supported introductory route until that workflow is verified. Deeper components and prototyping training belongs to mapped later modules.',
];

export type Milestone = { start: string; challenge: string; tools: string; save: string; later: string };
export const milestones: Record<string, Milestone> = Object.fromEntries([
  ['m00', 'Your current reasoning', 'Attempt an independent diagnostic', 'Paper and local notes', 'Original diagnostic and uncertainties', 'Personalize foundations; retain the original'],
  ['m01', 'Diagnostic and one familiar task', 'Observe, frame, sketch and defend decisions', 'Notes, paper; optional Figma basics', 'Walkthrough, flow, screens and decision note', 'Plan evidence collection in m02'],
  ['m02', 'Module 1 uncertainties and screens', 'Plan research, synthesize, prototype and revise', 'Notes, paper cards and consent script', 'Evidence chains and before/after practice', 'Reason about users in m04; prepare for Project 1'],
  ['m03', 'Module 1 screens', 'Stress-test type, color, spacing and states', 'Paper, local contrast calculator; optional Figma', 'Measured pairs, token sheet and craft comparison', 'Apply interface craft in Project 1 and systems in m13'],
  ['m04', 'Module 2 evidence and prototype', 'Challenge expectations, value and assumptions', 'Decision tables and optional free text chat', 'Needs, costs and a smallest-test brief', 'Choose a reachable Project 1 audience in m05'],
  ['m05', 'Practice evidence bank and participant-access inventory', 'Choose Project 1; investigate its problem', 'Local notes, consented conversations and paper grouping', 'Research plan, source log, synthesis and problem fragment', 'Inform m06 structure; recruitment gaps stay visible'],
  ['m06', 'Project 1 findings and content', 'Organize and test findability', 'Paper cards, text sitemap and manual tree test', 'Taxonomy, alternatives and findability observations', 'Build task flows in m07'],
  ['m07', 'Project 1 information structure', 'Design normal, failure and recovery paths', 'Paper flow cards; optional visual editor', 'Flows, wireframes and rejected alternatives', 'Build the interface in m08'],
  ['m08', 'Project 1 wireframes and m03 craft evidence', 'Develop responsive UI with guided tool practice', 'Validated free visual editor route with local equivalent', 'UI states, layout decisions and editable source', 'Support interaction and accessibility in m09–m11'],
  ['m09', 'Project 1 UI states', 'Specify interactions and motion alternatives', 'State storyboards and optional editor prototype', 'Transitions, feedback and reduced-motion intent', 'Choose prototype fidelity in m10'],
  ['m10', 'Project 1 interactions', 'Test and revise a bounded prototype', 'Paper or validated free prototype route', 'Consented test notes and revision fragment', 'Bring unresolved issues to m11'],
  ['m11', 'Project 1 UI and test evidence', 'Check accessibility and document limitations', 'Browser keyboard checks on working artifacts; paper specification otherwise', 'Accessibility evidence and Project 1 draft case study', 'Transfer learning to responsive web Project 2'],
  ['m12', 'Project 1 reflection and a new reachable audience', 'Choose Project 2; learn web behavior by building', 'Local text editor, HTML/CSS starter and browser tools', 'Responsive prototype and problem/evidence fragment', 'Extract reusable decisions in m13'],
  ['m13', 'Project 2 responsive prototype', 'Create a documented component system', 'Local CSS tokens and components; optional verified editor', 'System, usage rules, states and change history', 'Prepare delivery in m14'],
  ['m14', 'Project 2 prototype and system', 'Rehearse handoff and design QA', 'Local tickets, acceptance tables and browser', 'Handoff packet, QA findings and revisions', 'Define measurement questions in m15'],
  ['m15', 'Project 2 goals and QA evidence', 'Reason with metrics and experiments', 'Local spreadsheet; labelled synthetic dataset', 'Metric tree, uncertainty report and Project 2 draft', 'Avoid unsupported impact claims in all case studies'],
  ['m16', 'Two project reflections and a new audience', 'Choose Project 3; explore human control and AI failures', 'Text simulations and paper interfaces; optional free chatbot', 'Problem brief, evaluation scenarios and control design', 'Expand roles and service constraints in m17'],
  ['m17', 'Project 3 initial design and research questions', 'Reason about roles, dependencies and service trade-offs', 'Paper service maps and local decision tables', 'Role matrix, service blueprint and strategic choices', 'Scope independent delivery in m18'],
  ['m18', 'Project 3 scoped brief and evidence', 'Carry out an independent design/test/revision cycle', 'Appropriate previously learned free tools', 'Third project evidence, iteration and draft case study', 'Curate all three projects in m19'],
  ['m19', 'Three draft case studies and evidence banks', 'Select the strongest reasoning and tell a truthful story', 'Local document or slides; PDF export', 'Three case studies and portfolio presentation', 'Tailor evidence to real roles in m20'],
  ['m20', 'Portfolio and current role evidence', 'Practice applications, interviews and scope negotiation', 'Local documents and official job descriptions', 'Role matrix, resume and interview practice', 'Revise based on feedback; no employment guarantee'],
].map(([id, start, challenge, tools, save, later]) => [id, { start, challenge, tools, save, later }]));

export type ProjectBrief = { title: string; context: string; users: string; access: string; constraints: string; questions: string[] };
export const projectPacks: { id: string; title: string; modules: string; milestones: string[]; choices: ProjectBrief[] }[] = [
  {
    id: 'project-1', title: 'Project 1 · Research-led everyday service', modules: 'm05–m11',
    milestones: ['m05: select the brief based on access, investigate the problem and write an evidence-backed problem fragment.', 'm06–m07: save tested structure, alternative flows and the decision that selected one.', 'm08–m10: preserve UI and prototype versions, test observations and a revision fragment.', 'm11: add accessibility evidence, limitations and an initial case-study narrative.'],
    choices: [
      { title: 'Local booking', context: 'Explore how a small service handles finding availability, preparing for an appointment and changing a booking. The owner needs manageable coordination effort; do not assume a new app is the answer.', users: 'Adults who recently booked a local class, repair or personal service, plus the person coordinating it.', access: 'Choose a service where you can invite an organizer and recent customers with permission. Seek different experiences, including a changed or failed booking; label the sample exploratory.', constraints: 'Design for mobile use and plain language. Exclude payments, medical records and real booking transactions from the prototype. Staff capacity is a question to investigate.', questions: ['Where does uncertainty arise in the current process?', 'What information is needed before committing?', 'How are changes handled and who does the extra work?'] },
      { title: 'Community participation', context: 'Investigate joining and preparing for a neighborhood activity. Organizers need clear communication without taking on unmanageable administration.', users: 'Adult newcomers, returning attendees and an organizer of an accessible local activity.', access: 'Use a group you can approach legitimately. Ask separately for research participation; joining the activity is not consent to research.', constraints: 'Do not expose member lists or exact private addresses. Consider language, device and connectivity needs; prototype with invented logistical details labelled as such.', questions: ['What makes a newcomer hesitate or abandon joining?', 'How do people find preparation and access information?', 'What happens when plans change?'] },
    ],
  },
  {
    id: 'project-2', title: 'Project 2 · Responsive web product', modules: 'm12–m15',
    milestones: ['m12: investigate the chosen context, carry out focused research using earlier methods and save a responsive prototype with problem/evidence notes.', 'm13: document the component system, rejected choices and behavior at different widths.', 'm14: save delivery criteria, QA evidence and revisions.', 'm15: define metrics and an experiment proposal; keep synthetic analysis separate from real outcomes. Assemble the second draft case study.'],
    choices: [
      { title: 'Small-seller ordering', context: 'Explore how a small seller communicates product availability and receives order requests across phone and desktop. The business needs accurate requests and manageable follow-up.', users: 'An independent seller and adults who have recently tried ordering from a small business.', access: 'Recruit through an owner who agrees to the study; invite customers independently without receiving a private customer list.', constraints: 'Use mock products and no real checkout, payment or customer records. Address unavailable items and request confirmation. Keep implementation to a bounded local web prototype.', questions: ['Which product details affect a decision?', 'Where do customers and sellers misunderstand order status?', 'What changes between narrow and wide screens?'] },
      { title: 'Information discovery', context: 'Explore finding a suitable class, public activity or learning resource among many options. A provider needs discoverable information that is practical to maintain.', users: 'Adults recently comparing such options and someone responsible for maintaining the information.', access: 'Choose a topic with reachable searchers and a willing information owner. Use publicly accessible, attributable source material.', constraints: 'Avoid medical/legal advice directories. Record source freshness; use a small sample catalog and design empty, ambiguous and no-result states.', questions: ['Which criteria distinguish a suitable option?', 'What labels match the searcher’s language?', 'How do people judge whether information is current?'] },
    ],
  },
  {
    id: 'project-3', title: 'Project 3 · Complex workflow', modules: 'm16–m18',
    milestones: ['m16: choose the brief, investigate the existing workflow and define failure/evaluation scenarios. Both choices explore whether AI is appropriate.', 'm17: map roles, access, handoffs and service dependencies; preserve competing design options.', 'm18: independently prototype, evaluate and revise a bounded workflow; assemble evidence, limitations and the third draft case study.'],
    choices: [
      { title: 'Small-team request handling', context: 'Explore how a small volunteer or business team receives, assigns and resolves non-sensitive requests. The organization needs clear ownership and recoverable handoffs.', users: 'A request submitter, coordinator and person doing the work; roles may overlap in a small team.', access: 'Work with a consenting team and anonymized descriptions of past requests. Do not access its live internal system or confidential records.', constraints: 'Use synthetic request content. Include reassignment, duplicate requests and differing permissions. Evaluate AI assistance as an option, including a reasoned decision not to use it.', questions: ['Where does responsibility become unclear?', 'What information should each role see or change?', 'How is an incorrect assignment noticed and repaired?'] },
      { title: 'Human-reviewed AI assistance', context: 'Explore a tool that drafts responses to non-sensitive community or product questions while a person checks and approves them. Value depends on reducing effort without losing control or accuracy.', users: 'People drafting responses and people responsible for their quality.', access: 'Recruit adults who already answer repetitive questions. Collect anonymized workflow accounts, not private correspondence.', constraints: 'Prototype static response scenarios; no model API or automated sending. Include unsupported claims, uncertainty, correction, rejection and a manual route. All generated examples are simulations.', questions: ['What must a reviewer verify before approving?', 'When does reviewing take longer than drafting manually?', 'How should uncertainty and source gaps be shown?'] },
    ],
  },
];
export const caseStudySections = ['Context, users and business need', 'Research question, access, consent and limitations', 'Sources, competitive alternatives and synthesis', 'Problem and evidence that support it', 'Journey, structure and competing flows', 'Wireframes, UI, system and prototype decisions', 'Testing, accessibility and revisions', 'Outcomes actually measured, or a proposed measurement plan', 'Trade-offs, reflection and next questions'];
export const projectStart = 'Choose one brief per pack after listing whom you can ethically reach. Record the choice and reason in Projects/project-N/brief.md. Keep source-log.md, decisions.md and case-study.md beside it. With no participants yet, continue desk research and clearly labelled design exploration, record the recruitment gap and postpone user-evidence claims. Do not invent quotes, findings or impact.';
