export const modules = [
  {
    id: "m00",
    level: 0,
    title: "Find your starting point",
    hours: 10,
    prerequisites: [],
    areas: [1],
    primary: "R01",
    alternative: "R02",
    output: "Baseline flow, reflection and diagnostic review",
    status: "published",
  },
  {
    id: "m01",
    level: 1,
    title: "Product Design Foundations",
    hours: 14,
    prerequisites: ["m00"],
    areas: [1, 2, 3, 6, 7],
    primary: "R01",
    alternative: "R02",
    output: "Workshop flow and three screens; optional critique lessons",
    status: "published",
  },
  {
    id: "m02",
    level: 1,
    title: "Evidence to a Testable Design",
    hours: 10,
    prerequisites: ["m01"],
    areas: [3, 4, 10],
    primary: "R04",
    alternative: "R05",
    output: "Consent plan, findings, hypothesis, test and revision",
    status: "published",
  },
  {
    id: "m03",
    level: 1,
    title: "Visual foundations refresh",
    hours: 20,
    prerequisites: ["m01"],
    areas: [1, 8],
    primary: "R03",
    alternative: "R06",
    output: "Typography, color, spacing, grid and Gestalt comparison",
    status: "published",
  },
  {
    id: "m04",
    level: 1,
    title: "UX reasoning and product value",
    hours: 16,
    prerequisites: ["m02"],
    areas: [2, 3],
    primary: "R02",
    alternative: "R07",
    output: "Mental models, cognition, value proposition and MVP tradeoffs",
    status: "published",
  },
  {
    id: "m05",
    level: 2,
    title: "Research methods and synthesis",
    hours: 45,
    prerequisites: ["m04"],
    areas: [4],
    primary: "R08",
    alternative: "R04",
    output:
      "Desk and competitive research, interviews, observation, survey/diary plan, JTBD and journey",
    status: "published",
  },
  {
    id: "m06",
    level: 2,
    title: "Information architecture",
    hours: 25,
    prerequisites: ["m05"],
    areas: [5],
    primary: "R09",
    alternative: "R10",
    output: "Taxonomy, sitemap, card sort and manual tree test",
    status: "published",
  },
  {
    id: "m07",
    level: 2,
    title: "Flows and wireframes",
    hours: 30,
    prerequisites: ["m06"],
    areas: [6, 7],
    primary: "R11",
    alternative: "R12",
    output: "Onboarding, search, permissions, checkout and failure paths",
    status: "published",
  },
  {
    id: "m08",
    level: 3,
    title: "Interface craft and design tools",
    hours: 35,
    prerequisites: ["m03", "m07"],
    areas: [8],
    primary: "R06",
    alternative: "R03",
    output: "Responsive UI, content, grids and local components",
    status: "published",
  },
  {
    id: "m09",
    level: 3,
    title: "Interaction and motion",
    hours: 25,
    prerequisites: ["m08"],
    areas: [9],
    primary: "R13",
    alternative: "R02",
    output:
      "State transitions, keyboard behavior and reduced-motion alternative",
    status: "published",
  },
  {
    id: "m10",
    level: 3,
    title: "Prototyping and evaluation",
    hours: 35,
    prerequisites: ["m09"],
    areas: [10],
    primary: "R12",
    alternative: "R05",
    output: "Low to high fidelity prototype, test and evidence-led revision",
    status: "published",
  },
  {
    id: "m11",
    level: 3,
    title: "Accessible product design",
    hours: 35,
    prerequisites: ["m08"],
    areas: [11],
    primary: "R14",
    alternative: "R10",
    output: "Forms, contrast, focus, semantics and assistive-technology checks",
    status: "planned",
  },
  {
    id: "m12",
    level: 4,
    title: "Web foundations and responsive behavior",
    hours: 35,
    prerequisites: ["m11"],
    areas: [13],
    primary: "R15",
    alternative: "R16",
    output: "Local HTML/CSS/JS prototype with responsive and error states",
    status: "planned",
  },
  {
    id: "m13",
    level: 4,
    title: "Design systems",
    hours: 35,
    prerequisites: ["m12"],
    areas: [12],
    primary: "R17",
    alternative: "R06",
    output: "Tokens, components, variants, documentation and version change",
    status: "planned",
  },
  {
    id: "m14",
    level: 4,
    title: "Delivery and collaboration",
    hours: 30,
    prerequisites: ["m13"],
    areas: [16],
    primary: "R18",
    alternative: "R19",
    output: "Stories, acceptance criteria, handoff and design QA",
    status: "planned",
  },
  {
    id: "m15",
    level: 5,
    title: "Analytics and experiments",
    hours: 30,
    prerequisites: ["m14"],
    areas: [14],
    primary: "R20",
    alternative: "R07",
    output: "Metric tree, funnel, experiment and uncertainty report",
    status: "planned",
  },
  {
    id: "m16",
    level: 5,
    title: "AI-assisted work and AI products",
    hours: 30,
    prerequisites: ["m15"],
    areas: [15],
    primary: "R21",
    alternative: "R19",
    output:
      "Human control, uncertainty, failure, privacy and evaluation prototype",
    status: "planned",
  },
  {
    id: "m17",
    level: 5,
    title: "Strategy and complex systems",
    hours: 40,
    prerequisites: ["m16"],
    areas: [3, 17],
    primary: "R19",
    alternative: "R07",
    output:
      "B2B roles, consumer tradeoffs, service blueprint and stakeholder decisions",
    status: "planned",
  },
  {
    id: "m18",
    level: 5,
    title: "Independent product project",
    hours: 40,
    prerequisites: ["m17"],
    areas: [4, 10, 17],
    primary: "R19",
    alternative: "R22",
    output:
      "End-to-end third project with critique, repair and measured limitations",
    status: "planned",
  },
  {
    id: "m19",
    level: 6,
    title: "Portfolio and storytelling",
    hours: 45,
    prerequisites: ["m18"],
    areas: [17],
    primary: "R22",
    alternative: "R23",
    output: "Three evidence-based case studies and presentation",
    status: "planned",
  },
  {
    id: "m20",
    level: 6,
    title: "India and remote career preparation",
    hours: 35,
    prerequisites: ["m19"],
    areas: [17],
    primary: "R23",
    alternative: "R22",
    output:
      "Role evidence matrix, resume, profile, outreach drafts and interview practice",
    status: "planned",
  },
];
